---
- name: Prepare Consul services
  set_fact:
    consul_services:
      - id:   '{{ go_waku_service_name }}'
        name: '{{ go_waku_service_name }}'
        port: '{{ go_waku_libp2p_port }}'
        address: '{{ ansible_host }}'
        tags: ['env:{{ env }}', 'stage:{{ stage }}', 'go', 'waku']
        meta:
          node_enode: '{{ go_waku_node_multiaddr | default("unknown") }}'
        checks:
          - name: '{{ go_waku_service_name }}-health'
            type: 'tcp'
            tcp: 'localhost:{{ go_waku_libp2p_port }}'

      - id:   '{{ go_waku_service_name }}-rpc'
        name: '{{ go_waku_service_name }}-rpc'
        port: '{{ go_waku_rpc_port }}'
        address: '{{ ansible_host }}'
        tags: ['env:{{ env }}', 'stage:{{ stage }}', 'go', 'waku', 'rpc']
        checks:
          - name: '{{ go_waku_service_name }}-rpc-health'
            type: 'script'
            script: '{{ go_waku_service_path }}/rpc.sh get_waku_v2_debug_v1_info'

      - id:   '{{ go_waku_service_name }}-websocket'
        name: '{{ go_waku_service_name }}-websocket'
        port: '{{ go_waku_websocket_port }}'
        address: '{{ ansible_local.wireguard.address }}'
        tags: ['env:{{ env }}', 'stage:{{ stage }}', 'go', 'waku', 'websocket']
        meta:
          node_enode: '{{ go_waku_node_websocket | mandatory }}'
        checks:
          - name: '{{ go_waku_service_name }}-websocket-health'
            type: 'tcp'
            tcp: 'localhost:{{ go_waku_websocket_port }}'

      - id: '{{ go_waku_service_name }}-metrics'
        name: '{{ go_waku_service_name }}-metrics'
        port: '{{ go_waku_metrics_port }}'
        address: '{{ ansible_local.wireguard.address }}'
        tags: ['env:{{ env }}', 'stage:{{ stage }}', 'go', 'waku', 'metrics']
        meta:
          container: '{{ go_waku_service_name }}'
        checks:
          - name: '{{ go_waku_service_name }}-metrics-health'
            type: 'http'
            http: 'http://localhost:{{ go_waku_metrics_port }}/health'

- name: Disable Websocket service
  set_fact:
    consul_services: |
      {{ consul_services | rejectattr('name', 'match', '.*-websocket') | list }}
  when: not go_waku_websocket_enabled and not go_waku_websocket_secure_enabled

- name: Disable RPC service
  set_fact:
    consul_services: |
      {{ consul_services | rejectattr('name', 'match', '.*-rpc') | list }}
  when: not go_waku_rpc_enabled

- name: Create Consul services
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ go_waku_service_name | replace("-", "_") }}'
